# Generated by Django 5.1.3 on 2024-11-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Pekerja',
        ),
        migrations.DeleteModel(
            name='Pelanggan',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
